out_dir: results
metric_best: pearson # mse # f1
metric_agg: argmax
wandb:
  use: True
  project: Pascal
dataset:
  format: ''
  name: ncsu-v6-full-1-clique # edge_wt_only_coord  # Alternative: edge_wt_region_boundary
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: NCSUNode+LapPE # VOCNode+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: NCSUEdge # VOCEdge
  edge_encoder_bn: False
num_threads: 16

posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none

train:
  mode: custom
  batch_size: 1 # 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l2 # weighted_cross_entropy
gt:
  layer_type: None+Transformer
  layers: 4
  n_heads: 4 # 8
  dim_hidden: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 800
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
