out_dir: results
metric_best: f1
wandb:
  use: true
  project: Pascal
dataset:
  format: PyG-VN-VOCSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph
  task_type: classification
  transductive: false
  node_encoder: true
  node_encoder_name: VOCNode
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: VOCEdge
  edge_encoder_bn: false
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 2
  dim_inner: 128
  layer_type: hetero_gatedgcnconv
  act: relu
  residual: true
  dropout: 0.0
  agg: sum
  normalize_adj: false
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 5000
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
