# created by Chen
out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode #+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_virtual_gnn # custom_gnn
  loss_fun: l1
gnn:
  head: default # inductive_node
  layers_pre_mp: 0
  layers_mp: 2 # 8 #TODO: change back
  layers_post_mp: 3
  dim_inner: 166
  layer_type: gineconv
  batchnorm: True
  residual: True
  act: relu
  dropout: 0.0
  agg: mean #sum
  normalize_adj: False
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
