# does eigenvalues in laplace pos encoder help?
program: main.py
method: grid
parameters:
  gnn.layers_mp:
    values: [2]
  gnn.residual:
    values: [False]
  optim.max_epoch:
    values: [1000]
  posenc_LapPE.enable:
    values: [True]
  dataset.node_encoder_name:
    values: [NCSUNode+LapPE]
  posenc_LapPE.eigen.max_freqs:
    values: [30]
  dataset.name:
    values: ['ncsu-v6-full-1-clique', 'ncsu-v6-full-2-clique', 'ncsu-v6-full-3-clique', 'ncsu-v6-full-4-clique']
  num_threads:
    values: [2]

command:
  - ${env}
  - python
  - ${program}
  - "--cfg"
  - 'configs/GCN/NCSU-GCN.yaml'
  - "--repeat"
  - 4
  - ${args_no_hyphens}
