# try different convs
program: main.py
method: grid
parameters:
  gnn.layers_mp:
    values: [2,]
  gnn.layer_type:
    values: ['gcnconv']
  optim.max_epoch:
    values: [1000]
  posenc_LapPE.enable:
    values: [True]
  dataset.name:
    values: ['ncsu-v6-full-1-clique', 'ncsu-v6-full-2-clique', 'ncsu-v6-full-3-clique', 'ncsu-v6-full-4-clique']
  posenc_LapPE.eigen.max_freqs:
    values: [5, 10, 30]
  dataset.node_encoder_name:
    values: ['NCSUNode+LapPE']
  num_threads:
    values: [2]

command:
  - ${env}
  - python
  - ${program}
  - "--cfg"
  - 'configs/GCN/NCSU-GCN.yaml'
  - ${args_no_hyphens}
