# does add vn help?
program: main.py
method: grid
parameters:
  gnn.layers_mp:
    values: [4, 6] # [0, 1, 2, 3]
  gnn.residual:
    values: [True, False]
  optim.max_epoch:
    values: [1000]
  posenc_LapPE.enable:
    values: [False]
  dataset.node_encoder_name:
    values: [NCSUNode]
  dataset.name:
    values: ['ncsu-v6-full-1-clique', 'ncsu-v6-full-2-clique', 'ncsu-v6-full-3-clique', 'ncsu-v6-full-4-clique']
  num_threads:
    values: [2]

command:
  - ${env}
  - python
  - ${program}
  - "--cfg"
  - 'configs/GCN/NCSU-GCN.yaml'
  - ${args_no_hyphens}
