num_threads: 12
out_dir: results
metric_best: pearson # mse # f1
metric_agg: argmax
wandb:
  use: True
  project: Pascal
dataset:
  format: ''
  name: ncsu-v6-full-1-clique # edge_wt_region_boundary # edge_wt_only_coord  # Alternative: edge_wt_region_boundary
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: NCSUNode+LapPE
  node_encoder_bn: False
  edge_encoder: False
train:
  mode: custom
  batch_size: 2048 # 32
  eval_period: 1
  ckpt_period: 100
  sampler: neighbor # added to see if this makes pearson osicllates
model:
  type: gnn
  loss_fun: l2 # weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 2
  dim_inner: 128
  layer_type: gcnconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0 # 0.5
  agg: mean
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 1e-3 # 0.0005
  max_epoch: 1000
  scheduler: none # reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5

# added by Chen
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: sym
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none

posenc_LapPEVec:
  enable: False
  eigen:
    laplacian_norm: sym
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none

posenc_SignNet:
  enable: False
  eigen:
    laplacian_norm: sym
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  post_layers: 2
